name: Orpheus Symphony

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch: {}

permissions:
  contents: write

jobs:
  commit-strike:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Update commit strike file
        run: |
          echo "Daily commit strike generated on $(date -u '+%Y-%m-%d %H:%M:%S UTC')" > commit-strike.txt

      - name: Commit and push changes
        uses: EndBug/add-and-commit@v9
        with:
          message: "🔥 Daily commit strike"
          add: "commit-strike.txt"

 generate-snake:
     runs-on: ubuntu-latest

     steps:
       - name: Generate snake animation
         uses: Platane/snk/svg-only@v3
         with:
           github_user_name: CodeRei067
           outputs: |
             dist/github-contribution-grid-snake.svg

       - name: Push snake animation
         uses: crazy-max/ghaction-github-pages@v4
         with:
          target_branch: output
          build_dir: dist
         env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}